---
title: "Method"
description: Work in progress
---
From March 2020 to September 2021 COSMO-Denmark monitored people’s knowledge, perceptions, emotions, and behavioral reactions related to COVID-19. To this end COSMO-Denmark relied on a mixture of weekly, biweekly, and monthly repeated cross-sectional surveys and panel surveys. Participants in both the repeated cross-sectional surveys and the panel surveys were randomly recruited from the same potential participant pool, which was obtained as follows: In 2018 and 2020, following ethical and data protection approval, we received contact information for a total three representative samples regarding age and gender of approximately 100,000 adult Danish citizens from Statistics Denmark–– a Danish governmental organization that collects and prepares statistical information about Denmark and Danish citizens (https://www.dst.dk/en). From these samples, random non-overlapping subsets of XXXX-XXXX Danes were invited via the official digital mail system in Denmark (https://www.e-boks.com/danmark/en) every week from 2020-XX-XX to 2020-XXXX and every other week from 2020-XX-XX to 2021-XXX-XX to participate in the repeated cross-sectional surveys. A total of 35,070 entered the repeated cross-sectional survey and 31,024 fully completed it. Similarly, from the first of these three samples, a random subset of 15,000 Danes was invited to participate in the panel survey via the official digital mail system in Denmark in week XX, 2020. A total of 2,546 respondents participated in the first wave of the panel survey and were thus invited to participate in the subsequent waves of the survey on a weekly basis from 2020-XX-XX to 2020-XXXX and on monthly basis from 2020-XX-XX to 2021-XXX. All surveys were set up using formr and administered in Danish. On each measurement occasion, the repeated cross-sectional surveys comprised more items than the panel surveys did. Across the repeated cross-sectional surveys and the panel surveys some variables were assessed consistently, while others were only measured sporadically. An overview of all variables assessed in the repeated cross-sectional surveys and the panel surveys can be found at:

https://docs.google.com/spreadsheets/d/10TvgDYpPqIu0O5s8jx4TL0KF1NcfR9AUqm4AqNU2Tyc/edit?usp=sharing

The repeated cross-sectional surveys lasted around 25-30 min, and the panel surveys lasted around 10-15 min.Participation in both the repeated cross-sectional surveys was voluntary, and informed consent was obtained from all participants.
