---
title: "Publications"
description: |
  The following papers used COSMO Denmark data
---

## 2022/in press

Lilleholt, L., Zettler, I., Betsch, C., & Böhm, R. (under review). Pandemic fatigue: Measurement, correlates, and consequences. (Preprint: <https://psyarxiv.com/2xvbr/>)

Geiger, M., Rees, F., Lilleholt, L., Santana, A. P., Zettler, I. Wilhelm, O., Betsch, C., & Böhm, R. (2022). Measuring the 7Cs of vaccination readiness. [European Journal of Psychological Assessment, 38, 261-269](https://econtent.hogrefe.com/doi/10.1027/1015-5759/a000663?target=_blank).

Jirsa, V. K., Petkoski, S., Wang, H., Woodman, M., Fousek, J., Betsch, C., Felgendreff, L., Böhm, R., Lilleholt, L., Zettler, I., Faber, S. M., Shen, K., & McIntosh, A. R. (2022). Integrating psychosocial variables and societal diversity in epidemic models for predicting COVID-19 transmission dynamics. [PLOS Digital Health, 1, e0000098](https://doi.org/10.1371/journal.pdig.0000098?target=_blank). (Preprint: <https://www.medrxiv.org/content/10.1101/2020.08.12.20173252v1>)

Kaufmann, T. H., Lilleholt, L., Böhm, R., Zettler, I., & Heck, D. W. (2022). Sensitive attitudes and adherence to recommendations during the COVID-19 pandemic: Comparing direct and indirect questioning techniques. [Personality and Individual Differences, 190, 111525](https://doi.org/10.1016/j.paid.2022.111525?target=_blank){style="color: darkred ;"}.\
(Preprint: <https://psyarxiv.com/tp6ja/>)

Pummerer, L., Böhm, R., Lilleholt,L., Winter, K., Zettler, I., & Sassenberg, K. (2022). Conspiracy theories and their societal effects during the COVID-19 pandemic. [Social Psychological and Personality Science, 13, 49-59](https://doi.org/10.1177/19485506211000217?target=_blank).\
(Preprint: <https://psyarxiv.com/y5grn/>) 

Rees, F., Geiger, M., Lilleholt, L., Zettler, I., Betsch, C., Böhm, R., & Wilhelm, O. (2022). Measuring parents' readiness to vaccinate themselves and their children against COVID-19. Vaccine, 40, 3825-3834. (Preprint: <https://psyarxiv.com/wrgce/>)

Zettler, I., Schild, C., Lilleholt, L., Kroencke, L., Utesch, T., Moshagen,M., Böhm, R., Back, M. D., & Geukes, K. (2022). The role of personality in COVID-19 related perceptions, evaluations, and behaviours: Findings across five samples, nine traits, and 17 criteria. Social Psychological and Personality Science, 13, 299-310. (Preprint: <https://psyarxiv.com/pkm2a/>)

## 2021

Zettler, I., Lilleholt, L., Böhm, R., & Gondan, M. (2021). Comparing responses in repeated cross-sectional and panel studies: Results across eight weeks during the first COVID-19 lockdown in Denmark. [Psychological Assessment, 33, 691-704](https://doi.org/10.1037/pas0001048).

## 2020

Böhm, R., Lilleholt, L., Meineche, J. T., Strandsbjerg, C. F., Windfeld, A., Windfeld, F. C., & Zettler, I. (2020). The COVID-19 Snapshot Monitoring in Denmark. [Samfundsøkonomen, 4, 62-69](https://doi.org/10.7146/samfundsokonomen.v0i4.123562).

Böhm, R., Lilleholt, L., Zettler, I., & COSMO Denmark group (2020). Denmark COVID-19 Snapshot MOnitoring (COSMO Denmark): Monitoring knowledge, risk perceptions, preventive behaviours, and public trust in the current coronavirus outbreak in Denmark. [PsychArchives](https://doi.org/10.23668/psycharchives.2795).
